# Generated by Django 4.2.13 on 2024-12-24 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Coin')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('symbol', models.CharField(max_length=7, verbose_name='Ký hiệu')),
            ],
            options={
                'verbose_name': 'Loại tiền điện tử',
                'verbose_name_plural': 'Loại tiền điện tử',
                'db_table': 'crypto_type',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Số tiền')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nội dung chuyển khoản')),
            ],
            options={
                'verbose_name': 'Lịch sử giao dịch',
                'verbose_name_plural': 'Lịch sử giao dịch',
                'db_table': 'trans_history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('guid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Mã giao dịch bán')),
                ('transaction_type', models.CharField(default='sell', max_length=15, verbose_name='Loại giao dịch')),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Số lượng bán')),
                ('coin_name', models.CharField(blank=True, max_length=7, null=True, verbose_name='Tên coin')),
                ('price_transfer', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Giá chuyển đổi')),
                ('currency', models.CharField(default='VND', max_length=7, verbose_name='Loại tiền tệ chuyển đổi')),
                ('count_down', models.IntegerField(default=600, verbose_name='Thời hạn giao dịch (giây)')),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email người bán')),
                ('blockchain_net', models.CharField(default='BNB Smart Chain (BEP20)', max_length=255, verbose_name='Mạng lưới giao dịch')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên ngân hàng người bán')),
                ('bank_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số tài khoản')),
                ('bank_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài khoản')),
                ('wallet_address_in', models.CharField(default='0x80c763ce49c01c6df8425ce8bbff5e4758a422ed', max_length=42, verbose_name='Địa chỉ ví nhận')),
                ('fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Phí')),
                ('remain', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Số tiền thực nhận')),
                ('status', models.CharField(default='Pending', max_length=20, verbose_name='Trạng thái giao dịch')),
                ('admin_done', models.BooleanField(default=False, verbose_name='Admin xác nhận')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cryptotype', verbose_name='Coin')),
            ],
            options={
                'verbose_name': 'Giao dịch bán',
                'verbose_name_plural': 'Giao dịch bán',
                'db_table': 'sell_transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Khóa chính bảng giá tiền điện tử', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Giá')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm lấy giá')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cryptotype', verbose_name='Coin')),
            ],
            options={
                'verbose_name': 'Giá tiền điện tử',
                'verbose_name_plural': 'Giá tiền điện tử',
                'db_table': 'crypto_price',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='BuyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời điểm cập nhật')),
                ('guid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Mã giao dịch mua')),
                ('transaction_type', models.CharField(default='buy', max_length=15, verbose_name='Lọai giao dịch')),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Tên coin')),
                ('coin_name', models.CharField(blank=True, max_length=7, null=True, verbose_name='Coin')),
                ('price_transfer', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Giá chuyển đổi')),
                ('currency', models.CharField(default='VND', max_length=7, verbose_name='Tiền tệ')),
                ('count_down', models.IntegerField(default=600, verbose_name='Thời gian giao dịch hiệu lực (seconds)')),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email người mua')),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True, verbose_name='Địa chỉ ví mua')),
                ('blockchain_net', models.CharField(default='BNB Smart Chain (BEP20)', max_length=255, verbose_name='Mạng lưới blockchain')),
                ('fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Phí giao dịch')),
                ('remain', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Số coin thực nhận')),
                ('description_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nội dung chuyển khoản')),
                ('status', models.CharField(default='Pending', max_length=20, verbose_name='Trạng thái giao dịch')),
                ('admin_done', models.BooleanField(default=False, verbose_name='Xác nhận của Admin')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cryptotype', verbose_name='Coin')),
            ],
            options={
                'verbose_name': 'Giao dịch mua',
                'verbose_name_plural': 'Giao dịch mua',
                'db_table': 'buy_transactions',
                'ordering': ('-created_at',),
            },
        ),
    ]
